configs = [
    {
        'n': 4,
        'b': 4,
        's': 3,
        't': 5,
        'b_position': [(0,0),(0,3),(3,0),(3,3)],
        'd1': 6,
        'd2': 6,
        'recommend': False,
        'a1': False,
        'a2': False,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 4,
        'b': 4,
        's': 3,
        't': 1,
        'b_position': [(0,0),(0,3),(3,0),(3,3)],
        'd1': 6,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 5,
        'b': 4,
        's': 4,
        't': 1,
        'd1': 2,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 5,
        'b': 4,
        's': 4,
        't': 5,
        'd1': 6,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 8,
        'b': 5,
        's': 5,
        't': 1,
        'd1': 2,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 8,
        'b': 5,
        's': 5,
        't': 5,
        'd1': 2,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 8,
        'b': 6,
        's': 5,
        't': 1,
        'd1': 6,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
    {
        'n': 8,
        'b': 6,
        's': 5,
        't': 5,
        'd1': 6,
        'd2': 6,
        'recommend': False,
        'a1': True,
        'a2': True,
        'play_mode': ('ai', 'ai'),
        'heuristic': ('e1', 'e2')
    },
]